name: 'derpp_sweep'
method: grid
project: 'cl_sweeps2'
metric:
  goal: maximize
  name: valid/avg_acc
program: main.py

parameters:
  alpha: 
    values: 
    - 0.25
    - 0.5
    - 0.75
  beta:
    values:  
    - 0.5
    - 0.75
    - 1
  lr: 
    values:
    - 0.1
    - 0.01 
    - 0.001
  use_augs: 
    values: 
    - 1
  mem_size: 
    values: 
    - 20
    - 50 
    - 100
  dataset: 
    values: 
    - cifar10
    - cifar100
    - miniimagenet
  run: 
    values: 
    - 0 
    - 1
    - 2

  # defaults
  method:
    value: der++
  wandb_log:
    value: online
  task_free: 
    value: 1
  validation: 
    value: 1
