name: 'er_ace_new_aug_sweep'
project: 'new_aug_cl_sweeps'
method: grid
metric:
  goal: maximize
  name: valid/avg_acc
program: main.py

parameters:
  lr: 
    values:
    - 0.1
    - 0.05 
    - 0.01
  use_augs: 
    values: 
    - 1
  mem_size: 
    values: 
    - 20
    - 50 
    - 100
  dataset: 
    values: 
    - miniimagenet
  run: 
    values: 
    - 0 
    - 1

  # defaults
  method:
    value: er_ace
  wandb_log:
    value: online
  task_free: 
    value: 1
  validation: 
    value: 1
