name: 'er_task_free_sweep'
project: 'cl_sweeps2'
method: grid
metric:
  goal: maximize
  name: valid/avg_acc
program: main.py

parameters:
  lr: 
    values:
    - 0.1
    - 0.01
    - 0.001
  use_augs: 
    values: 
    - 0
    - 1
  mem_size: 
    values: 
    - 20
    - 50 
    - 100
  dataset: 
    values: 
    - cifar10
    - cifar100
    - miniimagenet
  run: 
    values: 
    - 0 
    - 1
    - 2

  # defaults
  method:
    value: er
  wandb_log:
    value: online
  task_free: 
    value: 1
  validation: 
    value: 1
